import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import AppClientProviders from "./AppClientProviders";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} font-sans antialiased`}>
        <AppClientProviders>{children}</AppClientProviders> 
      </body>
    </html>
  );
}
