/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace BlockFuseSMS {
  export type StudentDetailsStruct = {
    firstname: string;
    lastname: string;
    username: string;
    twitter: string;
    linkedin: string;
    github: string;
    track: BigNumberish;
    cohort: BigNumberish;
    isActive: boolean;
    finalScore: BigNumberish;
    studentAddress: AddressLike;
  };

  export type StudentDetailsStructOutput = [
    firstname: string,
    lastname: string,
    username: string,
    twitter: string,
    linkedin: string,
    github: string,
    track: bigint,
    cohort: bigint,
    isActive: boolean,
    finalScore: bigint,
    studentAddress: string
  ] & {
    firstname: string;
    lastname: string;
    username: string;
    twitter: string;
    linkedin: string;
    github: string;
    track: bigint;
    cohort: bigint;
    isActive: boolean;
    finalScore: bigint;
    studentAddress: string;
  };
}

export interface BlockFuseSMSInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "addStudentToCohort"
      | "addTrackToCohort"
      | "adminList"
      | "admins"
      | "attendance"
      | "attendanceRecords"
      | "cohortCount"
      | "cohorts"
      | "createCohort"
      | "disableStudent"
      | "enableStudent"
      | "getAllCohorts"
      | "getAttendanceByCohortAndTrack"
      | "getCohort"
      | "getCohortTracks"
      | "getStudent"
      | "getStudentAssesments"
      | "getStudentFinalScore"
      | "getStudentsByCohortAndTrack"
      | "hasAttendance"
      | "individualAttendanceRecord"
      | "logAttendance"
      | "recordStudentAssesment"
      | "registerStudent"
      | "removeAdmin"
      | "student"
      | "studentScore"
      | "superAdmin"
      | "testTrackToString"
      | "usernames"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AdminAdded"
      | "AdminRemoved"
      | "AssessmentRecorded"
      | "AttendanceLogged"
      | "CohortCreated"
      | "CohortTrackAdded"
      | "StudentAddedToCohort"
      | "StudentAddedToTrack"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addStudentToCohort",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addTrackToCohort",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "attendance",
    values: [BigNumberish, BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attendanceRecords",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cohortCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cohorts",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createCohort",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disableStudent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enableStudent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllCohorts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAttendanceByCohortAndTrack",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCohort",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCohortTracks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentAssesments",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentFinalScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStudentsByCohortAndTrack",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasAttendance",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "individualAttendanceRecord",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "logAttendance",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordStudentAssesment",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerStudent",
    values: [
      string,
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "student",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "studentScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "superAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testTrackToString",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "usernames",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addStudentToCohort",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTrackToCohort",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "adminList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "attendance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attendanceRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cohortCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cohorts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createCohort",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disableStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllCohorts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttendanceByCohortAndTrack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getCohort", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCohortTracks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStudent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getStudentAssesments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentFinalScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStudentsByCohortAndTrack",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasAttendance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "individualAttendanceRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logAttendance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordStudentAssesment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "student", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "studentScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "superAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testTrackToString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usernames", data: BytesLike): Result;
}

export namespace AdminAddedEvent {
  export type InputTuple = [adminAdded: AddressLike];
  export type OutputTuple = [adminAdded: string];
  export interface OutputObject {
    adminAdded: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [adminRemove: AddressLike];
  export type OutputTuple = [adminRemove: string];
  export interface OutputObject {
    adminRemove: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssessmentRecordedEvent {
  export type InputTuple = [
    studentAddress: AddressLike,
    studentScoreAdded: BigNumberish,
    totalScore: BigNumberish,
    time: BigNumberish,
    instructorAddress: AddressLike
  ];
  export type OutputTuple = [
    studentAddress: string,
    studentScoreAdded: bigint,
    totalScore: bigint,
    time: bigint,
    instructorAddress: string
  ];
  export interface OutputObject {
    studentAddress: string;
    studentScoreAdded: bigint;
    totalScore: bigint;
    time: bigint;
    instructorAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AttendanceLoggedEvent {
  export type InputTuple = [
    cohortId: BigNumberish,
    student: AddressLike,
    track: string,
    date: BigNumberish
  ];
  export type OutputTuple = [
    cohortId: bigint,
    student: string,
    track: string,
    date: bigint
  ];
  export interface OutputObject {
    cohortId: bigint;
    student: string;
    track: string;
    date: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CohortCreatedEvent {
  export type InputTuple = [cohortId: BigNumberish];
  export type OutputTuple = [cohortId: bigint];
  export interface OutputObject {
    cohortId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CohortTrackAddedEvent {
  export type InputTuple = [cohortId: BigNumberish, track: string];
  export type OutputTuple = [cohortId: bigint, track: string];
  export interface OutputObject {
    cohortId: bigint;
    track: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StudentAddedToCohortEvent {
  export type InputTuple = [studentAddress: AddressLike, cohort: BigNumberish];
  export type OutputTuple = [studentAddress: string, cohort: bigint];
  export interface OutputObject {
    studentAddress: string;
    cohort: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StudentAddedToTrackEvent {
  export type InputTuple = [
    cohortId: BigNumberish,
    track: string,
    student: AddressLike
  ];
  export type OutputTuple = [cohortId: bigint, track: string, student: string];
  export interface OutputObject {
    cohortId: bigint;
    track: string;
    student: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BlockFuseSMS extends BaseContract {
  connect(runner?: ContractRunner | null): BlockFuseSMS;
  waitForDeployment(): Promise<this>;

  interface: BlockFuseSMSInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<
    [adminAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  addStudentToCohort: TypedContractMethod<
    [_cohortId: BigNumberish, _student: AddressLike, _track: BigNumberish],
    [void],
    "nonpayable"
  >;

  addTrackToCohort: TypedContractMethod<
    [_cohortId: BigNumberish, _track: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  admins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  attendance: TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: AddressLike
    ],
    [boolean],
    "view"
  >;

  attendanceRecords: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, string] & { date: bigint; studentAddress: string }],
    "view"
  >;

  cohortCount: TypedContractMethod<[], [bigint], "view">;

  cohorts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        cohortId: bigint;
        totalStudents: bigint;
        startDate: bigint;
        endDate: bigint;
        duration: bigint;
      }
    ],
    "view"
  >;

  createCohort: TypedContractMethod<
    [_startDate: BigNumberish, _endDate: BigNumberish],
    [void],
    "nonpayable"
  >;

  disableStudent: TypedContractMethod<
    [_studentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  enableStudent: TypedContractMethod<
    [_studentAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  getAllCohorts: TypedContractMethod<
    [],
    [
      [bigint[], bigint[], bigint[], bigint[], bigint[], bigint[][]] & {
        ids: bigint[];
        totalStudents: bigint[];
        startDates: bigint[];
        endDates: bigint[];
        durations: bigint[];
        tracks: bigint[][];
      }
    ],
    "view"
  >;

  getAttendanceByCohortAndTrack: TypedContractMethod<
    [_cohortId: BigNumberish, _track: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;

  getCohort: TypedContractMethod<
    [_cohortId: BigNumberish],
    [
      [bigint, string[], bigint, bigint, bigint, bigint, string[][]] & {
        id: bigint;
        tracks: string[];
        totalStudents: bigint;
        startDate: bigint;
        endDate: bigint;
        duration: bigint;
        studentsByTrack: string[][];
      }
    ],
    "view"
  >;

  getCohortTracks: TypedContractMethod<
    [_cohortId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getStudent: TypedContractMethod<
    [_studentAddress: AddressLike],
    [BlockFuseSMS.StudentDetailsStructOutput],
    "view"
  >;

  getStudentAssesments: TypedContractMethod<
    [_studentWalletAddress: AddressLike],
    [bigint[]],
    "view"
  >;

  getStudentFinalScore: TypedContractMethod<
    [_studentWalletAddress: AddressLike],
    [bigint],
    "view"
  >;

  getStudentsByCohortAndTrack: TypedContractMethod<
    [_cohortId: BigNumberish, _track: BigNumberish],
    [BlockFuseSMS.StudentDetailsStructOutput[]],
    "view"
  >;

  hasAttendance: TypedContractMethod<
    [
      _studentAddress: AddressLike,
      _cohortId: BigNumberish,
      _track: BigNumberish,
      _day: BigNumberish
    ],
    [boolean],
    "view"
  >;

  individualAttendanceRecord: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[bigint, string] & { date: bigint; studentAddress: string }],
    "view"
  >;

  logAttendance: TypedContractMethod<
    [
      _studentAddress: AddressLike,
      _cohortId: BigNumberish,
      _track: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  recordStudentAssesment: TypedContractMethod<
    [_studentWalletAddress: AddressLike, _studentScore: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  registerStudent: TypedContractMethod<
    [
      _firstname: string,
      _lastname: string,
      _twitter: string,
      _linkedin: string,
      _github: string,
      _track: BigNumberish,
      _cohort: BigNumberish,
      _studentAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  removeAdmin: TypedContractMethod<
    [adminAddress: AddressLike],
    [boolean],
    "nonpayable"
  >;

  student: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        firstname: string;
        lastname: string;
        username: string;
        twitter: string;
        linkedin: string;
        github: string;
        track: bigint;
        cohort: bigint;
        isActive: boolean;
        finalScore: bigint;
        studentAddress: string;
      }
    ],
    "view"
  >;

  studentScore: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  superAdmin: TypedContractMethod<[], [string], "view">;

  testTrackToString: TypedContractMethod<
    [_track: BigNumberish],
    [string],
    "view"
  >;

  usernames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[adminAddress: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "addStudentToCohort"
  ): TypedContractMethod<
    [_cohortId: BigNumberish, _student: AddressLike, _track: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTrackToCohort"
  ): TypedContractMethod<
    [_cohortId: BigNumberish, _track: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "attendance"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      arg1: BigNumberish,
      arg2: BigNumberish,
      arg3: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "attendanceRecords"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, string] & { date: bigint; studentAddress: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "cohortCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cohorts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint] & {
        cohortId: bigint;
        totalStudents: bigint;
        startDate: bigint;
        endDate: bigint;
        duration: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "createCohort"
  ): TypedContractMethod<
    [_startDate: BigNumberish, _endDate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disableStudent"
  ): TypedContractMethod<[_studentAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "enableStudent"
  ): TypedContractMethod<[_studentAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllCohorts"
  ): TypedContractMethod<
    [],
    [
      [bigint[], bigint[], bigint[], bigint[], bigint[], bigint[][]] & {
        ids: bigint[];
        totalStudents: bigint[];
        startDates: bigint[];
        endDates: bigint[];
        durations: bigint[];
        tracks: bigint[][];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttendanceByCohortAndTrack"
  ): TypedContractMethod<
    [_cohortId: BigNumberish, _track: BigNumberish],
    [[string[], bigint[]]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCohort"
  ): TypedContractMethod<
    [_cohortId: BigNumberish],
    [
      [bigint, string[], bigint, bigint, bigint, bigint, string[][]] & {
        id: bigint;
        tracks: string[];
        totalStudents: bigint;
        startDate: bigint;
        endDate: bigint;
        duration: bigint;
        studentsByTrack: string[][];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCohortTracks"
  ): TypedContractMethod<[_cohortId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getStudent"
  ): TypedContractMethod<
    [_studentAddress: AddressLike],
    [BlockFuseSMS.StudentDetailsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudentAssesments"
  ): TypedContractMethod<
    [_studentWalletAddress: AddressLike],
    [bigint[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudentFinalScore"
  ): TypedContractMethod<
    [_studentWalletAddress: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudentsByCohortAndTrack"
  ): TypedContractMethod<
    [_cohortId: BigNumberish, _track: BigNumberish],
    [BlockFuseSMS.StudentDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasAttendance"
  ): TypedContractMethod<
    [
      _studentAddress: AddressLike,
      _cohortId: BigNumberish,
      _track: BigNumberish,
      _day: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "individualAttendanceRecord"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [[bigint, string] & { date: bigint; studentAddress: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "logAttendance"
  ): TypedContractMethod<
    [
      _studentAddress: AddressLike,
      _cohortId: BigNumberish,
      _track: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordStudentAssesment"
  ): TypedContractMethod<
    [_studentWalletAddress: AddressLike, _studentScore: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerStudent"
  ): TypedContractMethod<
    [
      _firstname: string,
      _lastname: string,
      _twitter: string,
      _linkedin: string,
      _github: string,
      _track: BigNumberish,
      _cohort: BigNumberish,
      _studentAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[adminAddress: AddressLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "student"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        string,
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        bigint,
        string
      ] & {
        firstname: string;
        lastname: string;
        username: string;
        twitter: string;
        linkedin: string;
        github: string;
        track: bigint;
        cohort: bigint;
        isActive: boolean;
        finalScore: bigint;
        studentAddress: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "studentScore"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "superAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "testTrackToString"
  ): TypedContractMethod<[_track: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "usernames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;

  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "AssessmentRecorded"
  ): TypedContractEvent<
    AssessmentRecordedEvent.InputTuple,
    AssessmentRecordedEvent.OutputTuple,
    AssessmentRecordedEvent.OutputObject
  >;
  getEvent(
    key: "AttendanceLogged"
  ): TypedContractEvent<
    AttendanceLoggedEvent.InputTuple,
    AttendanceLoggedEvent.OutputTuple,
    AttendanceLoggedEvent.OutputObject
  >;
  getEvent(
    key: "CohortCreated"
  ): TypedContractEvent<
    CohortCreatedEvent.InputTuple,
    CohortCreatedEvent.OutputTuple,
    CohortCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CohortTrackAdded"
  ): TypedContractEvent<
    CohortTrackAddedEvent.InputTuple,
    CohortTrackAddedEvent.OutputTuple,
    CohortTrackAddedEvent.OutputObject
  >;
  getEvent(
    key: "StudentAddedToCohort"
  ): TypedContractEvent<
    StudentAddedToCohortEvent.InputTuple,
    StudentAddedToCohortEvent.OutputTuple,
    StudentAddedToCohortEvent.OutputObject
  >;
  getEvent(
    key: "StudentAddedToTrack"
  ): TypedContractEvent<
    StudentAddedToTrackEvent.InputTuple,
    StudentAddedToTrackEvent.OutputTuple,
    StudentAddedToTrackEvent.OutputObject
  >;

  filters: {
    "AdminAdded(address)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminRemoved(address)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "AssessmentRecorded(address,int256,int256,uint256,address)": TypedContractEvent<
      AssessmentRecordedEvent.InputTuple,
      AssessmentRecordedEvent.OutputTuple,
      AssessmentRecordedEvent.OutputObject
    >;
    AssessmentRecorded: TypedContractEvent<
      AssessmentRecordedEvent.InputTuple,
      AssessmentRecordedEvent.OutputTuple,
      AssessmentRecordedEvent.OutputObject
    >;

    "AttendanceLogged(uint256,address,string,uint256)": TypedContractEvent<
      AttendanceLoggedEvent.InputTuple,
      AttendanceLoggedEvent.OutputTuple,
      AttendanceLoggedEvent.OutputObject
    >;
    AttendanceLogged: TypedContractEvent<
      AttendanceLoggedEvent.InputTuple,
      AttendanceLoggedEvent.OutputTuple,
      AttendanceLoggedEvent.OutputObject
    >;

    "CohortCreated(uint256)": TypedContractEvent<
      CohortCreatedEvent.InputTuple,
      CohortCreatedEvent.OutputTuple,
      CohortCreatedEvent.OutputObject
    >;
    CohortCreated: TypedContractEvent<
      CohortCreatedEvent.InputTuple,
      CohortCreatedEvent.OutputTuple,
      CohortCreatedEvent.OutputObject
    >;

    "CohortTrackAdded(uint256,string)": TypedContractEvent<
      CohortTrackAddedEvent.InputTuple,
      CohortTrackAddedEvent.OutputTuple,
      CohortTrackAddedEvent.OutputObject
    >;
    CohortTrackAdded: TypedContractEvent<
      CohortTrackAddedEvent.InputTuple,
      CohortTrackAddedEvent.OutputTuple,
      CohortTrackAddedEvent.OutputObject
    >;

    "StudentAddedToCohort(address,uint8)": TypedContractEvent<
      StudentAddedToCohortEvent.InputTuple,
      StudentAddedToCohortEvent.OutputTuple,
      StudentAddedToCohortEvent.OutputObject
    >;
    StudentAddedToCohort: TypedContractEvent<
      StudentAddedToCohortEvent.InputTuple,
      StudentAddedToCohortEvent.OutputTuple,
      StudentAddedToCohortEvent.OutputObject
    >;

    "StudentAddedToTrack(uint256,string,address)": TypedContractEvent<
      StudentAddedToTrackEvent.InputTuple,
      StudentAddedToTrackEvent.OutputTuple,
      StudentAddedToTrackEvent.OutputObject
    >;
    StudentAddedToTrack: TypedContractEvent<
      StudentAddedToTrackEvent.InputTuple,
      StudentAddedToTrackEvent.OutputTuple,
      StudentAddedToTrackEvent.OutputObject
    >;
  };
}
